### ISSUE TITLE
Compilation error with Xcode 14.0.1 into Version.swift

### ISSUE THREAD

**Issue by raizen-dev-w** [configcat/swift-sdk#29]
### Describe the bug

Using Xcode 14.0.1 (14A400) it does appear this compilation error
`'let' property 'major' may not be initialized directly; use "self.init(...)" or "self = ..." instead` onto Version.swift.

### To reproduce

Use ConfigCat as Pod in a project and try to build with Xcode Version 14.0.1 (14A400)

### Expected behavior

Build successfully without any errors.

### Screenshots
<img width="1007" alt="Captura de Tela 2022-10-27 às 15 27 50" src="https://user-images.githubusercontent.com/108472663/198369813-9b4920df-0c74-40ef-a323-a7cee7d3a0b6.png">

**Comment by z4kn4fein** [comment]
Hi @raizen-dev-w, thanks for the report! We'll investigate this issue and notify you here about the results.

**Comment by z4kn4fein** [comment]
Hi @raizen-dev-w, I wasn't able to repro this issue by importing the pod (`v9.2.2`) in a brand new project. Do you have any special configuration in yours? It would be the best if you could share a sample project where the issue occurs. Thanks!

**Comment by z4kn4fein** [comment]
Could you please try to use the new `v9.2.3` version?
